Repository FEMessage/element, pull requests merged in 2019-12, with the labels that each got.

#21 chore(deps): upgrade gren
  .grenrc.js
  package.json
  yarn.lock
Labels: dependencies

#24 fix: 使 drawer 不会挡住 message 和 notification
  packages/theme-chalk/src/common/var.scss
  packages/theme-chalk/src/message.scss
  packages/theme-chalk/src/notification.scss
Labels: bug

#26 feat: 增加手机号输入组件
  components.json
  examples/docs/en-US/input-phone.md
  examples/docs/es/input-phone.md
  examples/docs/fr-FR/input-phone.md
  examples/docs/zh-CN/input-phone.md
  examples/entry.js
  examples/nav.config.json
  package.json
  packages/input-phone/index.js
  packages/input-phone/src/const.js
  packages/input-phone/src/main.vue
  packages/theme-chalk/src/index.scss
  packages/theme-chalk/src/input-phone.scss
  src/index.js
  test/unit/specs/input-phone.spec.js
  types/element-ui.d.ts
  types/input-phone.d.ts
  yarn.lock
Labels: enhancement

#27 feat: 身份证输入框
  components.json
  examples/docs/en-US/input-id-card.md
  examples/docs/es/input-id-card.md
  examples/docs/fr-FR/input-id-card.md
  examples/docs/zh-CN/input-id-card.md
  examples/docs/zh-CN/input-phone.md
  examples/nav.config.json
  packages/empty/src/empty.svg
  packages/input-id-card/index.js
  packages/input-id-card/src/is-id-card.js
  packages/input-id-card/src/main.vue
  packages/theme-chalk/src/index.scss
  packages/theme-chalk/src/input-id-card.scss
  src/index.js
  test/unit/specs/input-id-card.spec.js
  types/element-ui.d.ts
  types/input-id-card.d.ts
Labels: enhancement
