Repository FEMessage/element, pull requests merged in 2020-08, with the labels that each got.

#62 fix(edit-table): oldValue 更新问题
  examples/docs/zh-CN/edit-table.md
  packages/edit-table/src/main.vue
Labels: bug

#66 feat: 为 el-select 添加 extra 插槽
  examples/docs/zh-CN/select.md
  packages/select/src/select.vue
Labels: enhancement

#67 ci: netlify.sh
  netlify.sh
Labels: ci

#65 feat: message-box support appendTarget
  examples/docs/zh-CN/message-box.md
  packages/message-box/src/main.js
Labels: enhancement
