Repository FEMessage/element, pull requests merged in 2020-09, with the labels that each got.

#71 feat: 提升 date-picker 选择日期用户体验
  packages/date-picker/src/panel/date-range.vue
  packages/date-picker/src/picker.vue
Labels: enhancement

#69 feat: timeline组件增加横版模式及时间戳插槽
  examples/docs/zh-CN/timeline.md
  package.json
  packages/theme-chalk/src/timeline-item.scss
  packages/theme-chalk/src/timeline.scss
  packages/timeline/src/dot.vue
  packages/timeline/src/item.vue
  packages/timeline/src/main.vue
  yarn.lock
Labels: enhancement

#73 chore: remove sass package
  package.json
  yarn.lock
Labels: chore

#75 feat: 树形数据的联动选择
  examples/docs/zh-CN/table.md
  packages/table/src/config.js
  packages/table/src/store/watcher.js
  packages/table/src/table.vue
  packages/table/src/util.js
Labels: enhancement

#77 docs: 更新文档链接
  .github/PULL_REQUEST_TEMPLATE.md
  FAQ.md
  examples/components/footer.vue
  examples/components/side-nav.vue
  examples/docs/en-US/custom-theme.md
  examples/docs/en-US/i18n.md
  examples/docs/en-US/input.md
  examples/docs/en-US/installation.md
  examples/docs/en-US/layout.md
  examples/docs/en-US/loading.md
  examples/docs/en-US/message-box.md
  examples/docs/en-US/message.md
  examples/docs/en-US/notification.md
  examples/docs/en-US/quickstart.md
  examples/docs/en-US/transition.md
  examples/docs/es/custom-theme.md
  examples/docs/es/i18n.md
  examples/docs/es/input.md
  examples/docs/es/installation.md
  examples/docs/es/layout.md
  examples/docs/es/loading.md
  examples/docs/es/message-box.md
  examples/docs/es/message.md
  examples/docs/es/notification.md
  examples/docs/es/quickstart.md
  examples/docs/es/transition.md
  examples/docs/fr-FR/custom-theme.md
  examples/docs/fr-FR/i18n.md
  examples/docs/fr-FR/input.md
  examples/docs/fr-FR/installation.md
  examples/docs/fr-FR/layout.md
  examples/docs/fr-FR/loading.md
  examples/docs/fr-FR/message-box.md
  examples/docs/fr-FR/message.md
  examples/docs/fr-FR/notification.md
  examples/docs/fr-FR/quickstart.md
  examples/docs/fr-FR/transition.md
  examples/docs/zh-CN/custom-theme.md
  examples/docs/zh-CN/i18n.md
  examples/docs/zh-CN/layout.md
  examples/docs/zh-CN/loading.md
  examples/docs/zh-CN/message-box.md
  examples/docs/zh-CN/message.md
  examples/docs/zh-CN/notification.md
  examples/docs/zh-CN/quickstart.md
  examples/docs/zh-CN/transition.md
  examples/pages/template/changelog.tpl
Labels: documentation

#78 feat: el-tree 支持虚拟滚动，提高性能
  examples/docs/en-US/tree.md
  examples/docs/zh-CN/tree.md
  package.json
  packages/tree/src/mixin/node.js
  packages/tree/src/tree-node.vue
  packages/tree/src/tree-virtual-node.vue
  packages/tree/src/tree.vue
  yarn.lock
Labels: enhancement

#76 feat: 增强 avatar
  examples/docs/en-US/avatar.md
  examples/docs/zh-CN/avatar.md
  packages/avatar/src/main.vue
  packages/theme-chalk/src/avatar.scss
  test/unit/specs/avatar.spec.js
Labels: enhancement
